stages:
  - androbuild
  - build
#pipelines:
#  stage: pipelines
#  script: /pub/ci/pipelines/pipelines.py
#  tags:
#    - old-other
#  only:
#    - branches
#    - merge_requests
#  except:
#    - schedules
androbuild:
  stage: androbuild
  tags:
  - android
  script: /test/android/androbuild.py
  allow_failure: true
  only:
    - branches
    - merge_requests
  except:
    - schedules
build:
  stage: build
  tags:
    - old-other
  only:
    - master
    - dev
    - tag
  except:
    - schedules
  variables:
    CI_REGISTRY_PROJECT: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  script:
    - docker build --no-cache --pull -f production/dockerfiles/flutter/Dockerfile -t "${CI_REGISTRY_PROJECT}/flutter:${CI_COMMIT_REF_NAME}" -t ${CI_REGISTRY_PROJECT}/flutter:${CI_COMMIT_REF_NAME} .
    - docker push "${CI_REGISTRY_PROJECT}/flutter:${CI_COMMIT_REF_NAME}"; docker push "${CI_REGISTRY_PROJECT}/flutter:${CI_COMMIT_REF_NAME}"
    - docker build --no-cache --pull -f production/dockerfiles/fastlane/Dockerfile -t "${CI_REGISTRY_PROJECT}/fastlane:${CI_COMMIT_REF_NAME}" -t ${CI_REGISTRY_PROJECT}/fastlane:${CI_COMMIT_REF_NAME} .
    - docker push "${CI_REGISTRY_PROJECT}/fastlane:${CI_COMMIT_REF_NAME}"; docker push "${CI_REGISTRY_PROJECT}/fastlane:${CI_COMMIT_REF_NAME}"