stages:
  - build
  - dddf
  - fork
  - gitlab
  - build
  - deploy


gitlab:
  stage: gitlab
  script:
    - echo "gitlab"

fork:
  stage: fork
  script:
    - echo "fork"

build_staging:
  stage: build
  script:
    - echo "build"
  only:
  - master

deploy_staging:
  stage: deploy
  script:
    - set
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  when: manual
  only:
  - master
