version: '3'

services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db:rw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    container_name: elasticsearch
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw

  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    restart: always
    environment:
      #      - root_timezone=UTC+7
      # adminpass: CthdqGfhjkm(СерыйПароль)
      - GRAYLOG_PASSWORD_SECRET=ZvC6LSURTAVVPns9UML0LZc3JfxFWehS7ZBzSwTvlifIrjB0c99pmuoEPB5nmawvPZbscPGOd7Xp5Z2kVmAfdupBSY8TZxRu
      #      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_ROOT_PASSWORD_SHA2=076bbb3d0c0eec99b032fda20362604c0a3580d3eb6a9d6b2ad50c3709ac97e8
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.userstory.ru/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # HTTP
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      #      - 12201:12201
      # GELF UDP
      #      - 12201:12201/udp

volumes:
  esdata1:
    driver: local
  mongodata:
    driver: local
