# Update fastlane automatically
#update_fastlane

default_platform(:android)

platform :android do
  desc "Build android aab"
  lane :build_android do
    # Build AAB
    sh "./flutter_build.sh"
  end

  desc "Deploy (Upload to play store)"
  lane :deploy_android do |options|
    upload_to_play_store(
#      track: options[:production] ? 'production' : options[:internal] ? 'internal' : options[:alpha] ? 'alpha' : 'beta',
      track: 'internal',
      json_key: '/data/key.json',
      package_name: 'com.userstory.optima_delivery_mobile',
      version_name: '0.1.12',
      version_code: '13',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      mapping: '/build/app/outputs/mapping/release/mapping.txt',
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end